jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        SRPS\BookingBundle\Entity\User: 
            algorithm: md5
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ORGANISER

    providers:
        main:
            entity: { class: SRPS\BookingBundle\Entity\User, property: username }      
        #in_memory:
        #    memory:
        #        users:
        #            # user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            # admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        #            fred:  { password: ryanpass, roles: 'ROLE_USER' }
        #            admin: { password: dragon, roles: 'ROLE_ADMIN' }

    firewalls:
        #dev:
        #    pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        #login:
        #    pattern:  ^/demo/secured/login$
        #    security: false

        secured_area:
            pattern:    ^/
            #form_login:
            #    check_path: /demo/secured/login_check
            #    login_path: /demo/secured/login
            logout: ~
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/admin/report, roles: ROLE_ORGANISER }        
        - { path: ^/admin, roles: ROLE_ADMIN }
