parameters:
#    srps_booking.example.class: SRPS\BookingBundle\Example

services:
    srps_booking:
        class: SRPS\BookingBundle\Service\Booking
        arguments: [ @doctrine.orm.entity_manager ]
