services:
    srps_stations:
        class: SRPS\BookingBundle\Service\Stations
        arguments: [@doctrine.orm.entity_manager]
    srps_booking:
        class: SRPS\BookingBundle\Service\Booking
        arguments: [@doctrine.orm.entity_manager]
    srps_sagepay:
        class: SRPS\BookingBundle\Service\Sagepay
        arguments: [@doctrine.orm.entity_manager]
    srps_reports:
        class: SRPS\BookingBundle\Service\Reports
        arguments: [@doctrine.orm.entity_manager]        
