parameters:
#    srps_booking.example.class: SRPS\BookingBundle\Example

services:
#    srps_booking.example:
#        class: %srps_booking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
