<?php

namespace SRPS\SantaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainRepository extends EntityRepository
{
}
