parameters:
#    srps_santa.example.class: SRPS\SantaBundle\Example

services:
#    srps_santa.example:
#        class: %srps_santa.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
